export const client = {
  name: "Calderstones Landscaping",
  tagline: "Professional Landscaper in Liverpool — Quality You Can Trust",
  description: "Professional landscaper services in Liverpool and surrounding areas. Trusted local experts with 46 Google reviews.",
  category: "Landscaper",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Liverpool",
  county: "",
  postcode: "",
  basedIn: "Liverpool",
  founderName: "Michael",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "5",
  reviewCount: "46",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Slogoman jr", rating: 5, text: "What a transformation to my garden. Completed on time and in full. Many thanks to Mike for his care, passion, flexibility and patience!!  We are delighted to have a wonderful space to enjoy as a family.  I cannot thank you enough and would highly recommend you and your great team. Thank you!!!! Sharon", date: "a week ago" },
    { name: "Mark Cummings", rating: 5, text: "I’ve known Mike and the team for over 15 years. They maintain the grounds of the estate in my previous employment. They are very knowledgeable, professional and brilliant at what they do. I recently used there services as I needed a mini digger & operator. Mike was there on time with no fuss and got the job done. I would highly recommend them. Brilliant company!", date: "a month ago" },
    { name: "Eleri Jones", rating: 5, text: "Absolutely fantastic service from Mike and the team - I would recommend their services without hesitation. They did a great job helping to clear snow & ice at short notice, and were polite, professional and friendly throughout - they couldn't do enough to help. Thank you Calderstones!", date: "2 months ago" },
    { name: "Cath Broderick", rating: 5, text: "Mike and the team were brilliant - created a lovely Laurel hedge making the area more sheltered and private and replanted in the front garden. Also did a superb job on a Venetian trellis on our wall at the rear of the house. We would not hesitate to recommend the Calderstones Landscaping guys", date: "3 months ago" },
    { name: "Carole", rating: 5, text: "Mike and the team 10/10. Superb fencing job, thank you so much keeping to time and leaving our gardens so tidy.", date: "4 months ago" },
    { name: "Leanne Jones", rating: 5, text: "Excellent work by Mike and team. Couldn’t be happier with the finished result. Would highly recommend!", date: "4 months ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Calderstones Landscaping | Professional Landscaper in Liverpool",
    description: "Professional landscaper in Liverpool. 5 stars on Google with 46 reviews. Quality workmanship guaranteed.",
  },
};
